services:
  - type: web
    name: deckreator-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/module-03-final-project-1.0.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render-java
    rootDir: backend